### ISSUE TITLE
Integrate Filering

### ISSUE THREAD

**Issue by Loryhoof** [ZAP-Wunschlachen/wunschlachen-library#1]
1. patient selects the treatment that he wants
2. patient selects the location he wants to go to (making sure the location has dentists that offer those treatments as well)
3. patient select the dentist (making sure that dentist has available time slots that also have the correct treatments in schedule rules)
4. patient selects date and time

...

1. we select treatment, then we get all schedule rules that have the selected treatment (in treatment_filter)
2. Now that we have all the matching schedule rules, we get their owner (the calendar).
3. Then we get the calendar's owner (the dentist)
4. We display all found calendar owners (dentists)
5. Patient can now select their preferred dentist.

ABOVE ARE DONE

6. We now show the available dates, for that dentist -> calendar -> schedule rule (need to somehow calculate that still)

We now have an array of all the matching dentists, that meet all the above requirements.
Now we need to get the available dates, which is just:

1. Get the schedule_rules that include the correct treatment_filter again (traverse schedule_rules, -> schedule_rules.calendars. Match with dentist.calendars)

- treatment_days (for example, ['monday', 'tuesday'])
- start_time / end_time ( '08:00', '15:15')
- treatment_date_filter ( check type, e.g. "gte" (greater than equal) date_1, ?date_2 )

**Comment by simgero** [comment]
Treatment Days filter are not working. Is this a known issue?
