### ISSUE TITLE
Create available timeslots page

### ISSUE THREAD

**Issue by Loryhoof** [ZAP-Wunschlachen/wunschlachen-library#6]

**Comment by simgero** [comment]
- [ ] This should Start with 9 Available Appointments (actually it's 3) 
![Image](https://github.com/user-attachments/assets/cda354f3-e3f7-41a9-b040-911a7a4eae78)

- [ ] This should Load again 9 new Appointments (actually it's loading 3) 
![Image](https://github.com/user-attachments/assets/9ebd0d1b-5693-49af-a8a5-c64e3d7f2a70)

- [ ] Remove the "zurück" and the Line
![Image](https://github.com/user-attachments/assets/a61bd47f-a93f-4947-a46f-024835b58590)
