### ISSUE TITLE
Create available dentist selection page

### ISSUE THREAD

**Issue by Loryhoof** [ZAP-Wunschlachen/wunschlachen-library#7]

**Comment by simgero** [comment]
![Image](https://github.com/user-attachments/assets/a6e9c9b9-c23c-4234-bddb-4f37af715e90)

Video: 
https://github.com/user-attachments/assets/398bc278-f9df-42e3-b6a0-3de4037312f6

- [ ] Limit the next available Appointments to 3
- [ ] Change The Text form "Termin Vereinbaren" to "Weitere Termine"
- [ ] Check the Video there is a Hard-coded Spacing on top of all Items and if you have a small device you have to scroll everything. Pls Align the Content in the middle of the screen and if there is more content @Julian-Ortlieb-OJ has to specify the min. Padding to the top
